package samuelvalentini.collection.videogame.enumeration;

public enum Piattaforma {
    //presi da https://en.wikipedia.org/wiki/Video_game_console
    _32X,
    _3DO,
    ATARI_2600,
    ATARI_5200,
    ATARI_7800,
    ATARI_JAGUAR,
    CD_I,
    COLECOVISION,
    DREAMCAST,
    GAME_BOY,
    GAME_BOY_ADVANCE,
    GAME_BOY_COLOR,
    GAMECUBE,
    GENESIS,
    INTELLIVISION,
    MAGNAVOX_ODYSSEY,
    MASTER_SYSTEM,
    NEO_GEO,
    NES,
    N_GAGE,
    NINTENDO_3DS,
    NINTENDO_64,
    NINTENDO_DS,
    NINTENDO_SWITCH,
    NINTENDO_SWITCH_2,
    PC,
    PLAYSTATION,
    PLAYSTATION_2,
    PLAYSTATION_3,
    PLAYSTATION_4,
    PLAYSTATION_5,
    PLAYSTATION_PORTABLE,
    PLAYSTATION_VITA,
    SEGA_CD,
    SEGA_SATURN,
    SNES,
    TURBOGRAFX_16,
    WII,
    WII_U,
    XBOX,
    XBOX_360,
    XBOX_ONE,
    XBOX_SERIES_X_S
}
